/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kamusi_proj;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.LinkedList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class newWord_UI extends javax.swing.JFrame{
    
    wordformDef p;
    Word word;
    Meanings m=new Meanings();
    WordForms f=new WordForms();
    WordDeriv d=new WordDeriv();
    WordExpression exp=new WordExpression();

    /**
     * Creates new form newWord_UI
     */
    
    public newWord_UI() {
        initComponents();
        try
        {
        f.allforms();
        }
        catch(SQLException e)
        {
            
        }
        LinkedList fo=f.getallforms();
        LinkedList fs=f.getfsymbols();
        for(int i=0;i<fo.size();i++)
        {
            allformscomb.addItem(""+fo.get(i));
        }
       word=new Word();
       LinkedList wtypeselect=word.allwordtypes();
       LinkedList allwords=word.allwords();
       LinkedList deriv=d.allderiv();
       for(int u=0;u<wtypeselect.size();u++)
        {
            wordtypescomb.addItem((String)wtypeselect.get(u));
        }
       for(int z=0;z<deriv.size();z++)
        {
            derivtypes.addItem((String)deriv.get(z));
        }
       for(int w=0;w<allwords.size();w++)
        {
            //derivs.addItem((String)allwords.get(w));
        }
       exp.allexp();
       LinkedList v=exp.getAllexptypes();
       for(int e=0;e<v.size();e++)
       {
       exptype.addItem((String)v.get(e));
       }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        previewlab = new javax.swing.JLabel();
        wordinsert = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        insertres = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        wordLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        worddefinition = new javax.swing.JTabbedPane();
        formtab = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        formdef = new javax.swing.JTextField();
        allformscomb = new javax.swing.JComboBox<>();
        formbutton = new javax.swing.JButton();
        meaningtab = new javax.swing.JPanel();
        meaning = new javax.swing.JTextField();
        examplef = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        meaningadd = new javax.swing.JButton();
        reference = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        derivtab = new javax.swing.JPanel();
        derivtypes = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        derivbutton = new javax.swing.JButton();
        deriv = new javax.swing.JTextField();
        expressiontab = new javax.swing.JPanel();
        exptype = new javax.swing.JComboBox<>();
        expbutton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        expfield = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        expmeaning = new javax.swing.JTextField();
        sectiontab = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        wordtypescomb = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        wordfield = new javax.swing.JTextField();

        jPanel2.setBackground(new java.awt.Color(240, 240, 28));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "winner", "wewe", "Item 3", "Item 4" }));

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("newword"); // NOI18N
        setPreferredSize(new java.awt.Dimension(953, 550));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(235, 235, 235));
        jPanel1.setMinimumSize(new java.awt.Dimension(953, 550));

        jPanel3.setOpaque(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setAutoscrolls(true);

        wordinsert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wordinsert.setForeground(new java.awt.Color(0, 0, 141));
        wordinsert.setText("insert word");
        wordinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordinsertActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 129));
        jLabel7.setText("preview");

        insertres.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        insertres.setForeground(new java.awt.Color(174, 24, 211));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(previewlab, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(insertres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wordinsert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(previewlab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insertres, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wordinsert, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(250, 250, 250));

        wordLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        wordLabel.setForeground(new java.awt.Color(0, 0, 179));
        wordLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/icons8_Add_New_48px_3.png"))); // NOI18N
        wordLabel.setText("Word form");
        wordLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wordLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                wordLabelMouseEntered(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 179));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/icons8_Add_New_48px_3.png"))); // NOI18N
        jLabel5.setText("Word Sections");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 179));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/icons8_Add_New_48px_3.png"))); // NOI18N
        jLabel6.setText("Word Expression");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 179));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/icons8_Add_New_48px_3.png"))); // NOI18N
        jLabel8.setText("word meaning");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 179));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/icons8_Add_New_48px_3.png"))); // NOI18N
        jLabel9.setText("Word derivation");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(wordLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(44, 44, 44)
                .addComponent(jLabel9)
                .addGap(53, 53, 53)
                .addComponent(jLabel6)
                .addGap(44, 44, 44)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        worddefinition.setBackground(new java.awt.Color(255, 255, 255));

        formtab.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 144));
        jLabel3.setText("form");

        formdef.setForeground(new java.awt.Color(0, 0, 197));

        allformscomb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        allformscomb.setForeground(new java.awt.Color(0, 0, 137));
        allformscomb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "type" }));

        formbutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        formbutton.setForeground(new java.awt.Color(0, 0, 199));
        formbutton.setText("Add");
        formbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formtabLayout = new javax.swing.GroupLayout(formtab);
        formtab.setLayout(formtabLayout);
        formtabLayout.setHorizontalGroup(
            formtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formtabLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(formtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formtabLayout.createSequentialGroup()
                        .addComponent(formdef, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(allformscomb, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formtabLayout.setVerticalGroup(
            formtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formtabLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(formtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formdef, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allformscomb, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(199, 199, 199)
                .addComponent(formbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        worddefinition.addTab("form", formtab);

        meaningtab.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 145));
        jButton1.setText("Add");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 162));
        jLabel4.setText("reference");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 162));
        jLabel12.setText("example");

        meaningadd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        meaningadd.setForeground(new java.awt.Color(0, 0, 134));
        meaningadd.setText("Add");
        meaningadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meaningaddActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 162));
        jLabel17.setText("meaning");

        javax.swing.GroupLayout meaningtabLayout = new javax.swing.GroupLayout(meaningtab);
        meaningtab.setLayout(meaningtabLayout);
        meaningtabLayout.setHorizontalGroup(
            meaningtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meaningtabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(meaningtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(meaningtabLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(meaningtabLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(meaningtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, meaningtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12))
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(meaningtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(meaningadd, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(examplef, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(meaning)
                            .addComponent(reference))
                        .addGap(101, 101, 101))))
        );
        meaningtabLayout.setVerticalGroup(
            meaningtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meaningtabLayout.createSequentialGroup()
                .addGroup(meaningtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(meaningtabLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(meaning, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, meaningtabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(meaningtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reference, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(meaningtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(examplef, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(44, 44, 44)
                .addComponent(meaningadd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
        );

        worddefinition.addTab(" meaning", meaningtab);

        derivtab.setBackground(new java.awt.Color(255, 255, 255));

        derivtypes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        derivtypes.setForeground(new java.awt.Color(0, 0, 113));
        derivtypes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "type" }));
        derivtypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derivtypesActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 115));
        jLabel13.setText("derivation");

        derivbutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        derivbutton.setForeground(new java.awt.Color(0, 0, 130));
        derivbutton.setText("Add");
        derivbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derivbuttonActionPerformed(evt);
            }
        });

        deriv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deriv.setForeground(new java.awt.Color(0, 0, 144));
        deriv.setText("derived word");
        deriv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                derivFocusGained(evt);
            }
        });

        javax.swing.GroupLayout derivtabLayout = new javax.swing.GroupLayout(derivtab);
        derivtab.setLayout(derivtabLayout);
        derivtabLayout.setHorizontalGroup(
            derivtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(derivtabLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(derivtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deriv, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(derivbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(derivtypes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        derivtabLayout.setVerticalGroup(
            derivtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(derivtabLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel13)
                .addGap(31, 31, 31)
                .addComponent(derivtypes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(deriv, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(derivbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        worddefinition.addTab(" derivation", derivtab);

        expressiontab.setBackground(new java.awt.Color(255, 255, 255));

        exptype.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exptype.setForeground(new java.awt.Color(0, 0, 114));
        exptype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "type" }));

        expbutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        expbutton.setForeground(new java.awt.Color(0, 0, 138));
        expbutton.setText("Add");
        expbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expbuttonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 111));
        jLabel10.setText("expression");

        expfield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        expfield.setForeground(new java.awt.Color(0, 0, 111));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 111));
        jLabel11.setText("meaning");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 111));
        jLabel16.setText("type");

        expmeaning.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        expmeaning.setForeground(new java.awt.Color(0, 0, 160));

        javax.swing.GroupLayout expressiontabLayout = new javax.swing.GroupLayout(expressiontab);
        expressiontab.setLayout(expressiontabLayout);
        expressiontabLayout.setHorizontalGroup(
            expressiontabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, expressiontabLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(expressiontabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(expressiontabLayout.createSequentialGroup()
                        .addGroup(expressiontabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(expressiontabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(expressiontabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(exptype, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(expmeaning, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(expbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(expressiontabLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(expfield, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
        );
        expressiontabLayout.setVerticalGroup(
            expressiontabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expressiontabLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(expressiontabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(30, 30, 30)
                .addGroup(expressiontabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exptype, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(37, 37, 37)
                .addGroup(expressiontabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(expmeaning, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(expbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        worddefinition.addTab("expression", expressiontab);

        sectiontab.setBackground(new java.awt.Color(255, 255, 255));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(0, 0, 125));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 110));
        jLabel14.setText("title");

        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(0, 0, 170));
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 115));
        jButton6.setText("Add");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 110));
        jLabel15.setText("content");

        javax.swing.GroupLayout sectiontabLayout = new javax.swing.GroupLayout(sectiontab);
        sectiontab.setLayout(sectiontabLayout);
        sectiontabLayout.setHorizontalGroup(
            sectiontabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectiontabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sectiontabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sectiontabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        sectiontabLayout.setVerticalGroup(
            sectiontabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectiontabLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(sectiontabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sectiontabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(59, 59, 59)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        worddefinition.addTab(" section", sectiontab);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(worddefinition)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(worddefinition)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        wordtypescomb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wordtypescomb.setForeground(new java.awt.Color(0, 0, 121));
        wordtypescomb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "word type" }));

        jLabel1.setBackground(new java.awt.Color(250, 250, 250));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 142));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Add_New_48px_2.png"))); // NOI18N
        jLabel1.setText("New word");

        wordfield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wordfield.setForeground(new java.awt.Color(0, 0, 146));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wordfield, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addComponent(wordfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wordtypescomb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wordtypescomb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        setSize(new java.awt.Dimension(966, 572));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void wordLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wordLabelMouseEntered
       // TODO add your handling code here:
    }//GEN-LAST:event_wordLabelMouseEntered

    private void wordLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wordLabelMouseClicked
   worddefinition.setSelectedIndex(0);
           // TODO add your handling code here:
    }//GEN-LAST:event_wordLabelMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        worddefinition.setSelectedIndex(1);  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        worddefinition.setSelectedIndex(2);  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        worddefinition.setSelectedIndex(3);  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       worddefinition.setSelectedIndex(4);   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void derivtypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derivtypesActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_derivtypesActionPerformed

    private void expbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expbuttonActionPerformed
        String expdef=expfield.getText();
        String ext=(String)exptype.getSelectedItem();
        String expmean=expmeaning.getText();
        if(!expdef.equals("") && !ext.equals("type") && !expmean.equals(""))
        {
            exp.setwexpression(expdef);
            exp.setwexptype(ext);
            exp.setwexpmeaning(expmean);
        }
        else{
            if(expdef.equals(""))
             new JOptionPane().showMessageDialog(null,"expression not specified","no epression",JOptionPane.INFORMATION_MESSAGE); 
            else if(ext.equals("type")){ new JOptionPane().showMessageDialog(null,"type not specified","no type",JOptionPane.INFORMATION_MESSAGE); }
            else{new JOptionPane().showMessageDialog(null,"expression meaning not specified","no expression",JOptionPane.INFORMATION_MESSAGE); }
        }
         word.setexpression(exp);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_expbuttonActionPerformed

    private void formbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formbuttonActionPerformed
         if(!(formdef.getText().equals("")) && !(allformscomb.getSelectedItem().equals("type")))
    {
       f=new WordForms(formdef.getText(),(String)allformscomb.getSelectedItem());
    }
    else
    {
        if(formdef.getText().equals("")){ new JOptionPane().showMessageDialog(null,"form not specified","must check",JOptionPane.INFORMATION_MESSAGE);}
        else{new JOptionPane().showMessageDialog(null,"form type","must check",JOptionPane.INFORMATION_MESSAGE);}
    }  
         
    word.setform(f);
        
     
// TODO add your handling code here:
    }//GEN-LAST:event_formbuttonActionPerformed

    private void meaningaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meaningaddActionPerformed
     String mn=null;
     String example=null;
     String ref=null;
        if(!(meaning.getText().equals("")) && !(examplef.getText().equals("")))
    {
      mn=meaning.getText();
      example=examplef.getText();
      ref=reference.getText();
      if(!ref.equals(""))
      {
      if(word.is_defined(ref))
      {
      m=new Meanings(mn,example,ref); 
      }
      else
      {
          
       new JOptionPane().showMessageDialog(null,"the reference does not exist","referencing failed",JOptionPane.INFORMATION_MESSAGE);    
      }
      }
      else{
        ref="noref";
        m.setReference(ref);
        m.setMeaning(mn);  
        m.setExample(example);  
      }
    }
    else
    {
        if(meaning.getText().equals("")){ new JOptionPane().showMessageDialog(null,"meaning must be specified","check meaning field",JOptionPane.INFORMATION_MESSAGE);}
        else{ new JOptionPane().showMessageDialog(null,"example must be specified","check example field",JOptionPane.INFORMATION_MESSAGE);}
      
    }  
    word.setmeaning(m);
     
     //word.setmeaning(m);
     //word.commitEntry();// TODO add your handling code here:
    }//GEN-LAST:event_meaningaddActionPerformed

    private void derivbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derivbuttonActionPerformed
        // TODO add your handling code here:
       String derivtype=(String)derivtypes.getSelectedItem();
       String derivdef=(String)deriv.getText();
       if(!derivtype.equals("type") && !(derivdef.equals("")||derivdef.equals("derived word")))
       {
          
           if(Word.is_defined(derivdef))
           {
           d.setderivtype(derivtype);
           d.setderivdef(derivdef);
           }
           else{
            new JOptionPane().showMessageDialog(null,"derived word reference does not exist","check derived word field",JOptionPane.INFORMATION_MESSAGE);}   
           }
       else
       {
           if(derivtype.equals("type")){new JOptionPane().showMessageDialog(null,"please choose a type","type not specified",JOptionPane.INFORMATION_MESSAGE);}
           else{new JOptionPane().showMessageDialog(null,"derived word must be specified","check derived word field",JOptionPane.INFORMATION_MESSAGE);}
       }
       word.setDeriv(d);
       
    }//GEN-LAST:event_derivbuttonActionPerformed

    private void derivFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_derivFocusGained
     deriv.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_derivFocusGained

    private void wordinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordinsertActionPerformed
        // TODO add your handling code here:
    if(!(wordfield.getText().equals("")) && !(wordtypescomb.getSelectedItem().equals("word type")))
    {
        if(!Word.is_defined(wordfield.getText()))
        {
        word.setWord(wordfield.getText());
        word.setwtype((String)wordtypescomb.getSelectedItem());
        }
        else
        {
          int conf= new JOptionPane().showConfirmDialog(null,"keep both words?","word already exists",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE); 
          if(conf!=JOptionPane.NO_OPTION && conf!=JOptionPane.CANCEL_OPTION && conf!=JOptionPane.CLOSED_OPTION)
          {
           word.setWord(wordfield.getText());
           word.setwtype((String)wordtypescomb.getSelectedItem());   
          }
        }
    }
    else if((wordfield.getText().equals(""))){
        new JOptionPane().showMessageDialog(null,"specify the word to insert","no word to insert",JOptionPane.INFORMATION_MESSAGE);
    }
    else{
        new JOptionPane().showMessageDialog(null,"choose a word type","no word type",JOptionPane.INFORMATION_MESSAGE);
    }
    if(word.commitEntry()){insertres.setText(wordfield.getText()+": insertion successful");}
    else{insertres.setText("word not inserted properly");}
    //System.out.println(word.allwords());
    }//GEN-LAST:event_wordinsertActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
             // TODO add your handling code here:
               if(evt.getKeyCode() == KeyEvent.VK_ENTER) 
     {
        if(!(wordfield.getText().equals("")) && !(wordtypescomb.getSelectedItem().equals("word type")))
    {
        word.setWord(wordfield.getText());
        word.setwtype((String)wordtypescomb.getSelectedItem());
    }
    else if((wordfield.getText().equals(""))){
        new JOptionPane().showMessageDialog(null,"specify the word to insert","no word to insert",JOptionPane.INFORMATION_MESSAGE);
    }
    else{
        new JOptionPane().showMessageDialog(null,"choose a word type","no word type",JOptionPane.INFORMATION_MESSAGE);
    }
    }              
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newWord_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newWord_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newWord_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newWord_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newWord_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> allformscomb;
    private javax.swing.JTextField deriv;
    private javax.swing.JButton derivbutton;
    private javax.swing.JPanel derivtab;
    private javax.swing.JComboBox<String> derivtypes;
    private javax.swing.JTextField examplef;
    private javax.swing.JButton expbutton;
    private javax.swing.JTextField expfield;
    private javax.swing.JTextField expmeaning;
    private javax.swing.JPanel expressiontab;
    private javax.swing.JComboBox<String> exptype;
    private javax.swing.JButton formbutton;
    private javax.swing.JTextField formdef;
    private javax.swing.JPanel formtab;
    private javax.swing.JLabel insertres;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField meaning;
    private javax.swing.JButton meaningadd;
    private javax.swing.JPanel meaningtab;
    private javax.swing.JLabel previewlab;
    private javax.swing.JTextField reference;
    private javax.swing.JPanel sectiontab;
    private javax.swing.JLabel wordLabel;
    private javax.swing.JTabbedPane worddefinition;
    private javax.swing.JTextField wordfield;
    private javax.swing.JButton wordinsert;
    private javax.swing.JComboBox<String> wordtypescomb;
    // End of variables declaration//GEN-END:variables
}
